### ISSUE TITLE
Nuget package is empty

### ISSUE THREAD

**Issue by skttl** [marcemarc/Moriyama.SuperDocTypeCreate#1]
What a great addition! #h5yr

I tried installing the nuget package, but apparently it doesn't contain any content files - only the package logo.

![image](https://user-images.githubusercontent.com/3726467/73732863-31a8a580-473b-11ea-9b8e-f14534f29422.png)

**Comment by marcemarc** [comment]
@skttl eek but what a logo!!!!! - I mucked up the nuspec file adding it in - apologies, can you try again now?

**Comment by skttl** [comment]
Much better, thanks!
